DROP TABLE patients;

CREATE TABLE patients (
    PAT_ID BIGINT NOT NULL AUTO_INCREMENT,
    PAT_AGE VARCHAR(55) NOT NULL DEFAULT '',
    PAT_WEIGHT VARCHAR(255) NOT NULL DEFAULT '',
    PAT_ETHN VARCHAR(55) NOT NULL DEFAULT '',
    NOTES TEXT,
    PRIMARY KEY (PAT_ID));


DROP TABLE reports;

CREATE TABLE reports (
    REP_ID BIGINT NOT NULL AUTO_INCREMENT,
    PAT_ID BIGINT NOT NULL,
    REP_DATE DATE NOT NULL,
    PAT_TEMP DOUBLE,
    PAT_HR INT,
    PAT_RESP DOUBLE,
    PAT_BPS INT,
    PAT_BPD INT,
    CRIT_NOTES TEXT,
    PRIMARY KEY (REP_ID));

DROP TABLE medications;

CREATE TABLE medications (
    MED_ID BIGINT NOT NULL AUTO_INCREMENT,
    PAT_ID BIGINT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    NAME VARCHAR(100) NOT NULL,
    DOSAGE VARCHAR(100) NOT NULL,
    PRIMARY KEY (MED_ID));

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;